### ISSUE TITLE
Support for alternative sshd port, updated base image

### ISSUE THREAD

**Issue by sopelt** [nicolas-van/ssh-socks-tunnel-docker#1]
Hi, this image is quite neat for some use-cases. Would you consider adding a parameter for alternate sshd ports (there are deployment scenarios like azure container instances where external mappings are not possible) as well as changing to a more recent alpine base image?

Would you accept a PR and update your image?

**Comment by nicolas-van** [comment]
Seems to be bad about Azure, port mapping is a quite important feature.

But yeah why not, make your pull request and I'll review it.

**Comment by sopelt** [comment]
Hey @nicolas-van, thank you for the swift reply.
I was thinking along the lines of https://github.com/nicolas-van/ssh-socks-tunnel-docker/pull/2 

The port mapping thing is not a general Azure restriction. When using AKS (Azure Kubernetes Services) you have all the typical things at your disposal including port mapping. When using ACI (Azure Container Instances, container groups) there (currently?) isn't a way to define port mappings.

ACI is a bit more approachable for some use-cases then AKS. ;)

**Comment by nicolas-van** [comment]
It's now merged.
